name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-production:
    name: Plan Production Changes
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: prd
      action: plan
      terraform_version: '1.14.6'
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      GH_PAT: ${{ secrets.GH_PAT }}
